export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBSTRACT = 'SUBSTRACT';
export const SAVECOUNTERSNAPSHOT = 'SAVECOUNTERSNAPSHOT';
export const DELETECOUNTERSNAPSHOT = 'DELETECOUNTERSNAPSHOT';